print("enter mark1")
m1=int(input())
print("enter mark2")
m2=int(input())
print("enter mark3")
m3=int(input())
print("enter mark4")
m4=int(input())
print("enter mark5")
m5=int(input())
total=m1+m2+m3+m4+m5
avg=total/5
print("mark1=",m1)
print("mark2=",m2)
print("mark3=",m3)
print("mark4=",m4)
print("mark5=",m5)
print("total=",total)
print("avg mark=",avg)